NemesisPlatform\Core\Account\Entity\AbstractMessage:
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: IDENTITY
  type: entity
  inheritanceType: SINGLE_TABLE
  fields:
    body:
      type: text
    created:
      type: datetime
      default: CURRENT_TIMESTAMP
    read:
      type: boolean
      column: '`read`'

  manyToOne:
    parent_message:
      targetEntity: NemesisPlatform\Core\Account\Entity\AbstractMessage
    recipient:
      targetEntity: NemesisPlatform\Core\Account\Entity\NamedUserInterface
