language: php

php:
  - 5.5
  - 5.6
  - 7
  - nightly
  - hhvm

env:
  - TESTS='behat'
  - TESTS='phpunit'

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - travis_retry composer self-update

install:
  - composer --prefer-source install

script:
  - mkdir -p build
  - if [ "$TESTS" = "phpunit" ]; then phpunit; fi;
  - if [ "$TESTS" = "behat" ]; then bin/behat -p console; fi;
