NemesisPlatform\Core\CMS\Entity\Block\AbstractBlock:
  type: entity
  inheritanceType: SINGLE_TABLE
  id:
      id:
          type: integer
          id: true
          generator:
              strategy: AUTO
  fields:
    description:
      type: string
