NemesisPlatform\Core\CMS\Entity\Block\SiteBlock:
  type: entity
  inheritanceType: SINGLE_TABLE
  id:
      id:
          type: integer
          id: true
          generator:
              strategy: AUTO

  fields:
    area:
      type: string
    weight:
      type: integer

  manyToOne:
    site:
      targetEntity: NemesisPlatform\Components\MultiSite\Entity\SiteInterface
      inversedBy: blocks

    block:
      targetEntity: NemesisPlatform\Core\CMS\Entity\Block\AbstractBlock

