NemesisPlatform\Core\CMS\Entity\File:
    inheritanceType: JOINED
    type: entity
    table: file
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mime:
            type: string
        filename:
            type: string
        storage_id:
            type: string
    lifecycleCallbacks: {  }
