NemesisPlatform\Core\CMS\Entity\PageRevision:
  type: entity
  table: PageRevision
  id:
      id:
          type: integer
          id: true
          generator:
              strategy: AUTO
  fields:
    content:
      type: text
    createdTime:
      type: datetime
  manyToOne:
    page:
      targetEntity: NemesisPlatform\Core\CMS\Entity\Page
      inversedBy: revisions
      joinColumn:
        onDelete: CASCADE
      cascade: ["remove"]
    author:
      targetEntity: NemesisPlatform\Core\Account\Entity\User
      fetch: EAGER
