NemesisPlatform\Core\CMS\Entity\ThemeInstance:
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  type: entity
  inheritanceType: SINGLE_TABLE
  fields:
    description:
      type: string
    theme:
      type: string
    config:
      type: json_array
