login_check:
    path: /login_check

logout:
    path: /logout

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin


_games_admin:
    resource: routing/games_admin.yml
    prefix: /admin

_games_user:
    resource: routing/games_user.yml

cms:
    resource: "@CMSBundle/Controller"
    type:     annotation
    prefix:   /

core:
    resource: "@CoreBundle/Controller"
    type:     annotation
    prefix:   /

game:
    resource: "@GameBundle/Controller"
    type:     annotation
    prefix:   /

page_by_alias:
    path: /{alias}
    defaults: { _controller: CMSBundle:Page:show }
    requirements:
      alias: .+
