<?php
/**
 * Created by PhpStorm.
 * User: Pavel Batanov <pavel@batanov.me>
 * Date: 25.02.2015
 * Time: 16:19
 */

namespace NemesisPlatform\Admin\Form\Type\Rule\Team;

use NemesisPlatform\Admin\Form\Type\Rule\AbstractRuleFormType;
use NemesisPlatform\Game\Entity\Rule\Team\MinMembersCountRule;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class MinMembersCountRuleFormType extends AbstractRuleFormType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder->add('min', 'integer');
    }


    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(['data_class' => MinMembersCountRule::class]);
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'rule_form_team_min_members_count';
    }
}
