NemesisPlatform\Components\Form\PersistentForms\Entity\Value\Type\TableValue:
  type: entity
  oneToMany:
    rows:
      targetEntity: NemesisPlatform\Components\Form\PersistentForms\Entity\Value\Type\TableRow
      mappedBy: table
      cascade: [all]
      orphanRemoval: true
