NemesisPlatform\Components\Form\Survey\Entity\SurveyQuestion:
  type: entity
  inheritanceType: SINGLE_TABLE
  id:
      id:
          type: integer
          id: true
          generator:
              strategy: IDENTITY
  fields:
    weight:
      type: integer

  manyToOne:
    field:
      targetEntity: \NemesisPlatform\Components\Form\PersistentForms\Entity\Field\AbstractField

    survey:
      targetEntity: NemesisPlatform\Components\Form\Survey\Entity\Survey
      inversedBy: questions
