NemesisPlatform\Components\Form\Survey\Entity\Survey:
  type: entity
  inheritanceType: SINGLE_TABLE
  id:
      id:
          type: integer
          id: true
          generator:
              strategy: IDENTITY
  fields:
    alias:
      type: string
    title:
      type: string
      nullable: true
    public:
      type: boolean
    editAllowed:
      type: boolean
    locked:
      type: boolean

  oneToMany:

    questions:
      targetEntity: NemesisPlatform\Components\Form\Survey\Entity\SurveyQuestion
      mappedBy: survey
      cascade: [all]
      orderBy:
        weight: ASC

    results:
      targetEntity: NemesisPlatform\Components\Form\Survey\Entity\SurveyResult
      mappedBy: survey
      orderBy:
        timeUpdated: DESC

  manyToOne:
    owner:
      targetEntity: Symfony\Component\Security\Core\User\UserInterface
