NemesisPlatform\Components\Form\Survey\Entity\SurveyResult:
  type: entity
  inheritanceType: SINGLE_TABLE
  id:
      id:
          type: integer
          id: true
          generator:
              strategy: IDENTITY
  indexes:
    time:
      columns: [timeUpdated]
  fields:
    timeCreated:
      type: datetime
    timeUpdated:
      type: datetime
  oneToMany:
    answers:
      targetEntity: NemesisPlatform\Components\Form\Survey\Entity\SurveyAnswer
      mappedBy: parent
      orphanRemoval: true
      cascade: [all]
      fetch: EAGER

  manyToOne:
    survey:
      targetEntity: NemesisPlatform\Components\Form\Survey\Entity\Survey
      inversedBy: results
    author:
      targetEntity: Symfony\Component\Security\Core\User\UserInterface

