NemesisPlatform\Game\Entity\Rule\AbstractRuleEntity:
  type: entity
  inheritanceType: SINGLE_TABLE
  table: Rule
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: IDENTITY
  fields:
    enabled:
      type: boolean
    strict:
      type: boolean
    description:
      type: string
