NemesisPlatform\Game\Entity\UserCategory:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
      name:
        type: string
    manyToOne:
      league:
        targetEntity: NemesisPlatform\Game\Entity\League
        inversedBy: categories
        cascade: [all]
    manyToMany:
      fields:
        targetEntity: NemesisPlatform\Components\Form\PersistentForms\Entity\Field\AbstractField
        cascade: [all]
        joinTable:
          name: category_fields
