NemesisPlatform\Modules\Game\QAGame\Entity\DecisionQuestion:
  type: entity
  inheritanceType: SINGLE_TABLE
  id:
      id:
          type: integer
          id: true
          generator:
              strategy: IDENTITY
  fields:
    title:
      type: string
    weight:
      type: integer

  manyToOne:
    field:
      targetEntity: \NemesisPlatform\Components\Form\PersistentForms\Entity\Field\AbstractField
    questionList:
      targetEntity: NemesisPlatform\Modules\Game\QAGame\Entity\QuestionList
      inversedBy: questions
