services:
  nemesis_platform.user_provider:
    class: NemesisPlatform\Core\Account\Security\UserProvider
    arguments: ["@doctrine.orm.entity_manager", "%admin_usernames%"]

  nemesis.security.anonymous_voter:
      class: NemesisPlatform\Core\Account\Security\Voters\AnonymousVoter
      public:     false
      arguments: [ @site.provider ]
      tags:
        - {name: security.voter}

  nemesis.security.user_voter:
      class: NemesisPlatform\Core\Account\Security\Voters\UserVoter
      public:     false
      arguments: [ @site.provider ]
      tags:
        - {name: security.voter}

