NemesisPlatform\Modules\Game\Core\Entity\Scenario\AbstractScenario:
    type: entity
    inheritanceType: SINGLE_TABLE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
      name:
        type: string
      code:
        type: string
