language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  - SYMFONY_VERSION='2.3.*' deps='no'
  - SYMFONY_VERSION='2.5.*' deps='no'
  - SYMFONY_VERSION='2.6.*' deps='no'
  - SYMFONY_VERSION='2.7.*' deps='no'
  - SYMFONY_VERSION='2.8.*' deps='no'

matrix:
    allow_failures:
        - php: hhvm

before_install:
  - travis_retry composer self-update

install:
    - composer require --no-update symfony/symfony=${SYMFONY_VERSION}
    - if [ "$deps" = "no" ]; then composer --prefer-source install; fi;
    - if [ "$deps" = "low" ]; then composer --prefer-source --prefer-lowest --prefer-stable update; fi;

script:
  - mkdir -p build
  - vendor/bin/phpunit --colors -c phpunit.xml --coverage-text
